apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment
  labels:
    app: notes-app
spec:
  #replicas: 2
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app-deployment
        image: hemanthravishankar/notepad:cb8fb1dc2b66adbc5bb12bd577e1378929acb370
        resources:
          limits:
            cpu: "200m"
          requests:
            cpu: "200m"
          
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
