apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment
  labels:
    app: notes-app
spec:
  #replicas: 2
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app-deployment
        image: hemanthravishankar/notepad:8deeb346761a47de42c040ce0270a63584915488
        resources:
          limits:
            cpu: "200m"
          requests:
            cpu: "200m"
          
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
