name: Repository Dispatch

on:
  repository_dispatch:
    types: [new-image]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply image name changes
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.ref }}
    - name: Change something
      run:  |
         cd kube_all_files
         echo ${{ github.event.client_payload.sha }}"
         sed -i 's|image:.*|image: hemanthravishankar/notepad:${{ github.event.client_payload.sha }}|g' deployment.yaml
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.PAT }}
        commit_message: update image version.
