name: Repository Dispatch

on:
  repository_dispatch:
    types: [new-image]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.client_payload.sha }}
        run:  |
         cd kube_all_files
         sed -i 's|image:.*|image: hemanthravishankar/notepad:"${{ github.event.client_payload.sha }}"|g' deployment.yaml
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply image name changes
